/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables;


import cn.kindg.jooq.generator.Indexes;
import cn.kindg.jooq.generator.JScrapy;
import cn.kindg.jooq.generator.Keys;
import cn.kindg.jooq.generator.tables.records.ScrapyAccountRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrapyAccount extends TableImpl<ScrapyAccountRecord> {

    private static final long serialVersionUID = -1116981813;

    /**
     * The reference instance of <code>j_scrapy.scrapy_account</code>
     */
    public static final ScrapyAccount SCRAPY_ACCOUNT = new ScrapyAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScrapyAccountRecord> getRecordType() {
        return ScrapyAccountRecord.class;
    }

    /**
     * The column <code>j_scrapy.scrapy_account.id</code>.
     */
    public final TableField<ScrapyAccountRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>j_scrapy.scrapy_account.username</code>.
     */
    public final TableField<ScrapyAccountRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>j_scrapy.scrapy_account.password</code>.
     */
    public final TableField<ScrapyAccountRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>j_scrapy.scrapy_account.state</code>. 账号信息状态，1有效，-1无效，0停用
     */
    public final TableField<ScrapyAccountRecord, Byte> STATE = createField("state", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("-1", org.jooq.impl.SQLDataType.TINYINT)), this, "账号信息状态，1有效，-1无效，0停用");

    /**
     * The column <code>j_scrapy.scrapy_account.create_time</code>.
     */
    public final TableField<ScrapyAccountRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>j_scrapy.scrapy_account</code> table reference
     */
    public ScrapyAccount() {
        this(DSL.name("scrapy_account"), null);
    }

    /**
     * Create an aliased <code>j_scrapy.scrapy_account</code> table reference
     */
    public ScrapyAccount(String alias) {
        this(DSL.name(alias), SCRAPY_ACCOUNT);
    }

    /**
     * Create an aliased <code>j_scrapy.scrapy_account</code> table reference
     */
    public ScrapyAccount(Name alias) {
        this(alias, SCRAPY_ACCOUNT);
    }

    private ScrapyAccount(Name alias, Table<ScrapyAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScrapyAccount(Name alias, Table<ScrapyAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ScrapyAccount(Table<O> child, ForeignKey<O, ScrapyAccountRecord> key) {
        super(child, key, SCRAPY_ACCOUNT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JScrapy.J_SCRAPY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCRAPY_ACCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ScrapyAccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SCRAPY_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScrapyAccountRecord> getPrimaryKey() {
        return Keys.KEY_SCRAPY_ACCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScrapyAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<ScrapyAccountRecord>>asList(Keys.KEY_SCRAPY_ACCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrapyAccount as(String alias) {
        return new ScrapyAccount(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScrapyAccount as(Name alias) {
        return new ScrapyAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScrapyAccount rename(String name) {
        return new ScrapyAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScrapyAccount rename(Name name) {
        return new ScrapyAccount(name, null);
    }
}
