/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator;


import cn.kindg.jooq.generator.tables.ScrapyAccount;
import cn.kindg.jooq.generator.tables.ScrapyData;
import cn.kindg.jooq.generator.tables.ScrapyDataDetail;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>j_scrapy</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SCRAPY_ACCOUNT_PRIMARY = Indexes0.SCRAPY_ACCOUNT_PRIMARY;
    public static final Index SCRAPY_DATA_PRIMARY = Indexes0.SCRAPY_DATA_PRIMARY;
    public static final Index SCRAPY_DATA_DETAIL_PRIMARY = Indexes0.SCRAPY_DATA_DETAIL_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SCRAPY_ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", ScrapyAccount.SCRAPY_ACCOUNT, new OrderField[] { ScrapyAccount.SCRAPY_ACCOUNT.ID }, true);
        public static Index SCRAPY_DATA_PRIMARY = Internal.createIndex("PRIMARY", ScrapyData.SCRAPY_DATA, new OrderField[] { ScrapyData.SCRAPY_DATA.ID }, true);
        public static Index SCRAPY_DATA_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", ScrapyDataDetail.SCRAPY_DATA_DETAIL, new OrderField[] { ScrapyDataDetail.SCRAPY_DATA_DETAIL.ID }, true);
    }
}
