/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator;


import cn.kindg.jooq.generator.tables.ScrapyAccount;
import cn.kindg.jooq.generator.tables.ScrapyData;
import cn.kindg.jooq.generator.tables.ScrapyDataDetail;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JScrapy extends SchemaImpl {

    private static final long serialVersionUID = -2125592471;

    /**
     * The reference instance of <code>j_scrapy</code>
     */
    public static final JScrapy J_SCRAPY = new JScrapy();

    /**
     * The table <code>j_scrapy.scrapy_account</code>.
     */
    public final ScrapyAccount SCRAPY_ACCOUNT = cn.kindg.jooq.generator.tables.ScrapyAccount.SCRAPY_ACCOUNT;

    /**
     * The table <code>j_scrapy.scrapy_data</code>.
     */
    public final ScrapyData SCRAPY_DATA = cn.kindg.jooq.generator.tables.ScrapyData.SCRAPY_DATA;

    /**
     * The table <code>j_scrapy.scrapy_data_detail</code>.
     */
    public final ScrapyDataDetail SCRAPY_DATA_DETAIL = cn.kindg.jooq.generator.tables.ScrapyDataDetail.SCRAPY_DATA_DETAIL;

    /**
     * No further instances allowed
     */
    private JScrapy() {
        super("j_scrapy", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ScrapyAccount.SCRAPY_ACCOUNT,
            ScrapyData.SCRAPY_DATA,
            ScrapyDataDetail.SCRAPY_DATA_DETAIL);
    }
}
