/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator;


import cn.kindg.jooq.generator.tables.ScrapyAccount;
import cn.kindg.jooq.generator.tables.ScrapyData;
import cn.kindg.jooq.generator.tables.ScrapyDataDetail;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in j_scrapy
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>j_scrapy.scrapy_account</code>.
     */
    public static final ScrapyAccount SCRAPY_ACCOUNT = cn.kindg.jooq.generator.tables.ScrapyAccount.SCRAPY_ACCOUNT;

    /**
     * The table <code>j_scrapy.scrapy_data</code>.
     */
    public static final ScrapyData SCRAPY_DATA = cn.kindg.jooq.generator.tables.ScrapyData.SCRAPY_DATA;

    /**
     * The table <code>j_scrapy.scrapy_data_detail</code>.
     */
    public static final ScrapyDataDetail SCRAPY_DATA_DETAIL = cn.kindg.jooq.generator.tables.ScrapyDataDetail.SCRAPY_DATA_DETAIL;
}
