/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables.daos;


import cn.kindg.jooq.generator.tables.ScrapyData;
import cn.kindg.jooq.generator.tables.records.ScrapyDataRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrapyDataDao extends DAOImpl<ScrapyDataRecord, cn.kindg.jooq.generator.tables.pojos.ScrapyData, Integer> {

    /**
     * Create a new ScrapyDataDao without any configuration
     */
    public ScrapyDataDao() {
        super(ScrapyData.SCRAPY_DATA, cn.kindg.jooq.generator.tables.pojos.ScrapyData.class);
    }

    /**
     * Create a new ScrapyDataDao with an attached configuration
     */
    public ScrapyDataDao(Configuration configuration) {
        super(ScrapyData.SCRAPY_DATA, cn.kindg.jooq.generator.tables.pojos.ScrapyData.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.kindg.jooq.generator.tables.pojos.ScrapyData object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchById(Integer... values) {
        return fetch(ScrapyData.SCRAPY_DATA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.kindg.jooq.generator.tables.pojos.ScrapyData fetchOneById(Integer value) {
        return fetchOne(ScrapyData.SCRAPY_DATA.ID, value);
    }

    /**
     * Fetch records that have <code>data_source IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchByDataSource(String... values) {
        return fetch(ScrapyData.SCRAPY_DATA.DATA_SOURCE, values);
    }

    /**
     * Fetch records that have <code>data_type IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchByDataType(String... values) {
        return fetch(ScrapyData.SCRAPY_DATA.DATA_TYPE, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchByCreateTime(LocalDateTime... values) {
        return fetch(ScrapyData.SCRAPY_DATA.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchByRemark(String... values) {
        return fetch(ScrapyData.SCRAPY_DATA.REMARK, values);
    }

    /**
     * Fetch records that have <code>data_count IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyData> fetchByDataCount(Long... values) {
        return fetch(ScrapyData.SCRAPY_DATA.DATA_COUNT, values);
    }
}
