/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables.daos;


import cn.kindg.jooq.generator.tables.ScrapyDataDetail;
import cn.kindg.jooq.generator.tables.records.ScrapyDataDetailRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrapyDataDetailDao extends DAOImpl<ScrapyDataDetailRecord, cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail, Integer> {

    /**
     * Create a new ScrapyDataDetailDao without any configuration
     */
    public ScrapyDataDetailDao() {
        super(ScrapyDataDetail.SCRAPY_DATA_DETAIL, cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail.class);
    }

    /**
     * Create a new ScrapyDataDetailDao with an attached configuration
     */
    public ScrapyDataDetailDao(Configuration configuration) {
        super(ScrapyDataDetail.SCRAPY_DATA_DETAIL, cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchById(Integer... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail fetchOneById(Integer value) {
        return fetchOne(ScrapyDataDetail.SCRAPY_DATA_DETAIL.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchByTitle(String... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.TITLE, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchByContent(String... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.CONTENT, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchByCreateTime(LocalDateTime... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchByRemark(String... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.REMARK, values);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<cn.kindg.jooq.generator.tables.pojos.ScrapyDataDetail> fetchBySource(String... values) {
        return fetch(ScrapyDataDetail.SCRAPY_DATA_DETAIL.SOURCE, values);
    }
}
