/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ScrapyData implements Serializable {

    private static final long serialVersionUID = 1145322151;

    private Integer id;
    private String dataSource;
    private String dataType;
    private LocalDateTime createTime;
    private String remark;
    private Long dataCount;

    public ScrapyData() {
    }

    public ScrapyData(ScrapyData value) {
        this.id = value.id;
        this.dataSource = value.dataSource;
        this.dataType = value.dataType;
        this.createTime = value.createTime;
        this.remark = value.remark;
        this.dataCount = value.dataCount;
    }

    public ScrapyData(
            Integer id,
            String dataSource,
            String dataType,
            LocalDateTime createTime,
            String remark,
            Long dataCount
    ) {
        this.id = id;
        this.dataSource = dataSource;
        this.dataType = dataType;
        this.createTime = createTime;
        this.remark = remark;
        this.dataCount = dataCount;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDataSource() {
        return this.dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getDataCount() {
        return this.dataCount;
    }

    public void setDataCount(Long dataCount) {
        this.dataCount = dataCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScrapyData (");

        sb.append(id);
        sb.append(", ").append(dataSource);
        sb.append(", ").append(dataType);
        sb.append(", ").append(createTime);
        sb.append(", ").append(remark);
        sb.append(", ").append(dataCount);

        sb.append(")");
        return sb.toString();
    }
}
