/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrapyDataDetail implements Serializable {

    private static final long serialVersionUID = -1849566485;

    private Integer       id;
    private String        title;
    private String        content;
    private LocalDateTime createTime;
    private String        remark;
    private String        source;

    public ScrapyDataDetail() {}

    public ScrapyDataDetail(ScrapyDataDetail value) {
        this.id = value.id;
        this.title = value.title;
        this.content = value.content;
        this.createTime = value.createTime;
        this.remark = value.remark;
        this.source = value.source;
    }

    public ScrapyDataDetail(
        Integer       id,
        String        title,
        String        content,
        LocalDateTime createTime,
        String        remark,
        String        source
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
        this.remark = remark;
        this.source = source;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScrapyDataDetail (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(createTime);
        sb.append(", ").append(remark);
        sb.append(", ").append(source);

        sb.append(")");
        return sb.toString();
    }
}
