/*
 * This file is generated by jOOQ.
 */
package cn.kindg.jooq.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScrapyAccount implements Serializable {

    private static final long serialVersionUID = 141114261;

    private Integer       id;
    private String        username;
    private String        password;
    private Byte          state;
    private LocalDateTime createTime;

    public ScrapyAccount() {}

    public ScrapyAccount(ScrapyAccount value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.state = value.state;
        this.createTime = value.createTime;
    }

    public ScrapyAccount(
        Integer       id,
        String        username,
        String        password,
        Byte          state,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.state = state;
        this.createTime = createTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Byte getState() {
        return this.state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScrapyAccount (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(state);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
